# Generated by Django 4.2.7 on 2026-06-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soil', '0002_alter_soilrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('soil_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soil.soilrecord')),
            ],
        ),
    ]
