# Generated by Django 4.2.7 on 2026-06-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
